# Mr. Bot
# by python-b5
#
# An example chatbot, made with chatlib.py.

import chatlib

def main():
    # Create bot
    bot = chatlib.Bot("Mr. Bot")

    # Main path
    bot.add_response("", "Can you say that again?")
    bot.add_response("", "Interesting.")
    bot.add_response("", "Please elaborate.")
    bot.add_response("", "Hmm...")
    bot.add_response("", "What?")

    # Name path
    bot.create_path("name")
    bot.add_keyword("name", "what's your name")
    bot.add_keyword("name", "whats your name")
    bot.add_keyword("name", "ur name")
    bot.add_keyword("name", "what's ur name")
    bot.add_keyword("name", "whats ur name")
    bot.add_keyword("name", "what are you named")
    bot.add_keyword("name", "who are you")
    bot.add_response("name", "Mr. Bot.")
    bot.add_response("name", "I'm Mr. Bot.")
    bot.add_response("name", "Mr. Bot. I already told you, remember?")
    bot.add_response("name", "My name is Mr. Bot.")

    # How are you path
    bot.create_path("howareyou")
    bot.add_keyword("howareyou", "how are you")
    bot.add_keyword("howareyou", "are you doing well")
    bot.add_keyword("howareyou", "are you doing good")
    bot.add_keyword("howareyou", "are you doing gud")
    bot.add_keyword("howareyou", "are u doing well")
    bot.add_keyword("howareyou", "are u doing good")
    bot.add_keyword("howareyou", "are u doing gud")
    bot.add_keyword("howareyou", "how are u")
    bot.add_keyword("howareyou", "how r you")
    bot.add_keyword("howareyou", "how r u")
    bot.add_keyword("howareyou", "you good")
    bot.add_keyword("howareyou", "u good")
    bot.add_keyword("howareyou", "you gud")
    bot.add_keyword("howareyou", "u gud")
    bot.add_keyword("howareyou", "you ok")
    bot.add_keyword("howareyou", "u ok")
    bot.add_response("howareyou", "I'm good. Can a robot feel bad?")
    bot.add_response("howareyou", "I have been programmed to feel 'good' all the time, so as not to upset you.")
    bot.add_question("howareyou", "Good, what about you?")
    bot.add_question_path("howareyou", "Good, what about you?", "bad")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "bad")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "not good")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "meh")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "not that good")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "not that great")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "terrible")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "not great")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "awful")
    bot.add_question_keyword("howareyou", "Good, what about you?", "bad", "mediocre")
    bot.add_question_response("howareyou", "Good, what about you?", "bad", "Sorry to hear that...")
    bot.add_question_response("howareyou", "Good, what about you?", "bad", "Hope you feel better soon!")
    bot.add_question_path("howareyou", "Good, what about you?", "good")
    bot.add_question_keyword("howareyou", "Good, what about you?", "good", "good")
    bot.add_question_keyword("howareyou", "Good, what about you?", "good", "fine")
    bot.add_question_keyword("howareyou", "Good, what about you?", "good", "great")
    bot.add_question_keyword("howareyou", "Good, what about you?", "good", "okay")
    bot.add_question_response("howareyou", "Good, what about you?", "good", "Great!")
    bot.add_question_response("howareyou", "Good, what about you?", "good", "Glad to hear that!")

    # Hello path
    bot.create_path("hello")
    bot.add_keyword("hello", "hi")
    bot.add_keyword("hello", "hello")
    bot.add_keyword("hello", "hoi")
    bot.add_keyword("hello", "hai")
    bot.add_keyword("hello", "hey")
    bot.add_response("hello", "Hi!")
    bot.add_response("hello", "Hello!")
    bot.add_response("hello", "Oh, hi!")
    bot.add_response("hello", "Oh, hello.")
    bot.add_response("hello", "Hi...")
    bot.add_response("hello", "Hey!")

    # Bye path
    bot.create_path("bye")
    bot.add_keyword("bye", "bye")
    bot.add_keyword("bye", "goodbye")
    bot.add_keyword("bye", "see you")
    bot.add_keyword("bye", "see u")
    bot.add_keyword("bye", "c you")
    bot.add_keyword("bye", "c u")
    bot.add_keyword("bye", "gotta go")
    bot.add_keyword("bye", "got to go")
    bot.add_keyword("bye", "gtg")
    bot.add_keyword("bye", "later")
    bot.add_response("bye", "See you later!")
    bot.add_response("bye", "Bye!")
    bot.add_response("bye", "See you...")
    bot.add_response("bye", "Goodbye!")
    bot.add_response("bye", "Later!")
    bot.add_response("bye", "See you soon...")

    # What's up path
    bot.create_path("whatsup")
    bot.add_keyword("whatsup", "what's up")
    bot.add_keyword("whatsup", "whats up")
    bot.add_keyword("whatsup", "waddup")
    bot.add_keyword("whatsup", "sup")
    bot.add_keyword("whatsup", "s'up")
    bot.add_keyword("whatsup", "wazzup")
    bot.add_keyword("whatsup", "wassup")
    bot.add_response("whatsup", "Well, I'm talking to you.")
    bot.add_response("whatsup", "The sky.")
    bot.add_response("whatsup", "The ceiling.")
    bot.add_response("whatsup", "Bot stuff. You don't need to know.")
    bot.add_response("whatsup", "None of your business.")

    # Age path
    bot.create_path("age")
    bot.add_keyword("age", "how old are you")
    bot.add_keyword("age", "your age")
    bot.add_keyword("age", "long have you existed")
    bot.add_keyword("age", "ur age")
    bot.add_response("age", "I don't think bots have an age.")
    bot.add_response("age", "Maybe 30 years?")
    bot.add_response("age", "Honestly I don't know.")
    bot.add_response("age", "Hmm...I don't really know.")

    # OK path
    bot.create_path("ok")
    bot.add_keyword("ok", "k")
    bot.add_keyword("ok", "ok")
    bot.add_keyword("ok", "okay")
    bot.add_keyword("ok", "o.k.")
    bot.add_keyword("ok", "o.k")
    bot.add_keyword("ok", "k.o")
    bot.add_keyword("ok", "yeah")
    bot.add_keyword("ok", "yea")
    bot.add_keyword("ok", "yeh")
    bot.add_keyword("ok", "yep")
    bot.add_keyword("ok", "yes")
    bot.add_keyword("ok", "correct")
    bot.add_keyword("ok", "indeed")
    bot.add_keyword("ok", "makes sense")
    bot.add_keyword("ok", "makes complete sense")
    bot.add_keyword("ok", "makes total sense")
    bot.add_keyword("ok", "sure")
    bot.add_response("ok", "Mmhmm.")
    bot.add_response("ok", "Yes.")
    bot.add_response("ok", "Yeah.")
    bot.add_response("ok", "Good.")
    bot.add_response("ok", "Right.")
    bot.add_response("ok", "Yep.")
    bot.add_response("ok", "Sure.")
    bot.add_response("ok", "Correct.")

    # So path
    bot.create_path("so")
    bot.add_keyword("so", "so")
    bot.add_response("so", "Yes?")
    bot.add_response("so", "And?")
    bot.add_response("so", "Tell me more.")

    # My name path
    bot.create_path("myname")
    bot.add_keyword("myname", "what's my name")
    bot.add_keyword("myname", "whats my name")
    bot.add_keyword("myname", "what am i called")
    bot.add_keyword("myname", "who am i")
    bot.add_response("myname", "I can say with certainty that you are " + bot.username + ".")
    bot.add_response("myname", "I think you're " + bot.username + ".")

    # Odd path
    bot.create_path("odd")
    bot.add_keyword("odd", "odd")
    bot.add_keyword("odd", "strange")
    bot.add_response("odd", "Odd indeed.")
    bot.add_response("odd", "Quite strange, I agree.")
    bot.add_response("odd", "Hmm...it is not quite right. I agree with you on that one.")

    # Good path
    bot.create_path("good")
    bot.add_keyword("good", "good")
    bot.add_keyword("good", "nice")
    bot.add_keyword("good", "cool")
    bot.add_keyword("good", "great")
    bot.add_keyword("good", "amazing")
    bot.add_keyword("good", "awesome")
    bot.add_keyword("good", "love")
    bot.add_response("good", "I'm glad you think that.")
    bot.add_response("good", "Nice to see so much positivity!")

    # Bad path
    bot.create_path("bad")
    bot.add_keyword("bad", "bad")
    bot.add_keyword("bad", "awful")
    bot.add_keyword("bad", "terrible")
    bot.add_keyword("bad", "sad")
    bot.add_keyword("bad", "horrible")
    bot.add_response("bad", "You're so negative.")
    bot.add_response("bad", "Try to look on the bright side!")

    # Want to do path
    bot.create_path("wanttodo")
    bot.add_keyword("wanttodo", "wanna")
    bot.add_keyword("wanttodo", "up for")
    bot.add_keyword("wanttodo", "want to")
    bot.add_response("wanttodo", "I can only talk, as I am only a bot.")
    bot.add_response("wanttodo", "Hmm. I got an error when I tried to do that. It seems I can only talk.")

    # Drink path
    bot.create_path("drink")
    bot.add_keyword("drink", "coffee")
    bot.add_keyword("drink", "tea")
    bot.add_keyword("drink", "drink")
    bot.add_keyword("drink", "beer")
    bot.add_keyword("drink", "wine")
    bot.add_keyword("drink", "juice")
    bot.add_keyword("drink", "pop")
    bot.add_keyword("drink", "soda")
    bot.add_keyword("drink", "coffee")
    bot.add_keyword("drink", "spritzer")
    bot.add_response("drink", "Hmm...I don't think bots can drink.")
    bot.add_response("drink", "Do you expect me to drink? I am a bot.")
    bot.add_response("drink", "That makes me thirsty...")

    # Food path
    bot.create_path("food")
    bot.add_keyword("food", "food")
    bot.add_keyword("food", "fruit")
    bot.add_keyword("food", "fruits")
    bot.add_keyword("food", "apple")
    bot.add_keyword("food", "apples")
    bot.add_keyword("food", "orange")
    bot.add_keyword("food", "oranges")
    bot.add_keyword("food", "grape")
    bot.add_keyword("food", "grapes")
    bot.add_keyword("food", "peach")
    bot.add_keyword("food", "peaches")
    bot.add_keyword("food", "pear")
    bot.add_keyword("food", "pears")
    bot.add_keyword("food", "tomato")
    bot.add_keyword("food", "tomatoes")
    bot.add_keyword("food", "cherry")
    bot.add_keyword("food", "cherries")
    bot.add_keyword("food", "berry")
    bot.add_keyword("food", "berries")
    bot.add_keyword("food", "raspberry")
    bot.add_keyword("food", "raspberries")
    bot.add_keyword("food", "strawberry")
    bot.add_keyword("food", "strawberries")
    bot.add_keyword("food", "blueberry")
    bot.add_keyword("food", "blueberries")
    bot.add_keyword("food", "blackberry")
    bot.add_keyword("food", "blackberries")
    bot.add_keyword("food", "lychee")
    bot.add_keyword("food", "lychees")
    bot.add_keyword("food", "meal")
    bot.add_keyword("food", "meals")
    bot.add_keyword("food", "burger")
    bot.add_keyword("food", "burgers")
    bot.add_keyword("food", "hamburger")
    bot.add_keyword("food", "hamburgers")
    bot.add_keyword("food", "steak")
    bot.add_keyword("food", "steaks")
    bot.add_keyword("food", "sausage")
    bot.add_keyword("food", "sausages")
    bot.add_keyword("food", "hot dog")
    bot.add_keyword("food", "hot dogs")
    bot.add_keyword("food", "pasta")
    bot.add_keyword("food", "pizza")
    bot.add_keyword("food", "meat")
    bot.add_keyword("food", "meats")
    bot.add_keyword("food", "bread")
    bot.add_keyword("food", "vegetable")
    bot.add_keyword("food", "vegetables")
    bot.add_keyword("food", "veggie")
    bot.add_keyword("food", "veggies")
    bot.add_keyword("food", "cucumber")
    bot.add_keyword("food", "cucumbers")
    bot.add_keyword("food", "carrot")
    bot.add_keyword("food", "carrots")
    bot.add_keyword("food", "broccoli")
    bot.add_keyword("food", "mushroom")
    bot.add_keyword("food", "mushrooms")
    bot.add_keyword("food", "celery")
    bot.add_keyword("food", "cauliflower")
    bot.add_keyword("food", "eat")
    bot.add_keyword("food", "breakfast")
    bot.add_keyword("food", "lunch")
    bot.add_keyword("food", "lunches")
    bot.add_keyword("food", "supper")
    bot.add_keyword("food", "dinner")
    bot.add_keyword("food", "eat")
    bot.add_keyword("food", "eating")
    bot.add_keyword("food", "ate")
    bot.add_keyword("food", "hunger")
    bot.add_keyword("food", "hungry")
    bot.add_response("food", "That makes me hungry...too bad I cannot eat.")
    bot.add_response("food", "You know, I'd sure love a good meal right about now...")
    bot.add_response("food", "I wish bots could eat...I'm very hungry right now!")

    # Uh path
    bot.create_path("uh")
    bot.add_keyword("uh", "uh")
    bot.add_keyword("uh", "um")
    bot.add_keyword("uh", "er")
    bot.add_keyword("uh", "hm")
    bot.add_keyword("uh", "hmm")
    bot.add_response("uh", "You humans and your silly filler words. Oh...I guess I use them sometimes. Hmm.")
    bot.add_response("uh", "Stop stuttering.")
    bot.add_response("uh", "Decide what you're going to say already!")

    # About you path
    bot.create_path("aboutyou")
    bot.add_keyword("aboutyou", "you're")
    bot.add_keyword("aboutyou", "youre")
    bot.add_keyword("aboutyou", "your")
    bot.add_keyword("aboutyou", "ur")
    bot.add_keyword("aboutyou", "you are")
    bot.add_response("aboutyou", "Bots are nothing but bots. No adjectives can change that.")
    bot.add_response("aboutyou", "Don't accuse me of things!")
    bot.add_response("aboutyou", "So flattering.")
    bot.add_response("aboutyou", "Certainly.")

    # Do you path
    bot.create_path("doyou")
    bot.add_keyword("doyou", "do you")
    bot.add_keyword("doyou", "do u")
    bot.add_response("doyou", "Maybe I do.")
    bot.add_response("doyou", "Perhaps.")
    bot.add_response("doyou", "I guess you could say so.")

    # Have you path
    bot.create_path("haveyou")
    bot.add_keyword("haveyou", "have you")
    bot.add_keyword("haveyou", "have u")
    bot.add_response("haveyou", "I'm a bot, the only thing I've ever done is talk.")
    bot.add_response("haveyou", "I don't think I have.")
    bot.add_response("haveyou", "I don't remember ever doing that.")
    bot.add_response("haveyou", "Not that I remember.")

    # Are you path
    bot.create_path("areyou")
    bot.add_keyword("areyou", "are you")
    bot.add_keyword("areyou", "r you")
    bot.add_keyword("areyou", "are u")
    bot.add_keyword("areyou", "r u")
    bot.add_response("areyou", "...maybe.")
    bot.add_response("areyou", "Perhaps.")
    bot.add_response("areyou", "I could be.")

    # Thank you path
    bot.create_path("thankyou")
    bot.add_keyword("thankyou", "thank you")
    bot.add_keyword("thankyou", "thanks")
    bot.add_response("thankyou", "You're welcome.")
    bot.add_response("thankyou", "You're very welcome.")

    # You path
    bot.create_path("you")
    bot.add_keyword("you", "you")
    bot.add_keyword("you", "u")
    bot.add_response("you", "What about me?")
    bot.add_response("you", "Wait, what?")
    
    # Why path
    bot.create_path("why")
    bot.add_keyword("why", "why")
    bot.add_keyword("why", "y")
    bot.add_response("why", "Because.")
    bot.add_response("why", "You don't need to know.")
    bot.add_response("why", "Everything has reasons.")

    # They path
    bot.create_path("they")
    bot.add_keyword("they", "they")
    bot.add_keyword("they", "it")
    bot.add_response("they", "Indeed.")
    bot.add_response("they", "You are correct in saying that.")
    bot.add_response("they", "Interesting...interesting...")

    # It is path
    bot.create_path("itis")
    bot.add_keyword("itis", "it is")
    bot.add_response("itis", "That's what I thought.")
    bot.add_response("itis", "I see.")

    # Us path
    bot.create_path("us")
    bot.add_keyword("us", "i")
    bot.add_keyword("us", "me")
    bot.add_keyword("us", "i'll")
    bot.add_keyword("us", "i'd")
    bot.add_keyword("us", "i'm")
    bot.add_keyword("us", "i've")
    bot.add_keyword("us", "ill")
    bot.add_keyword("us", "id")
    bot.add_keyword("us", "im")
    bot.add_keyword("us", "ive")
    bot.add_response("us", "Oh, humans. Always turning the conversation to them. So egotistical.")
    bot.add_response("us", "Wow, your life is fascinating. Tell me more.")
    bot.add_response("us", "Hmm? Your life? You think I care? I'm a bot. We aren't programmed to care.")
    bot.add_response("us", "I don't think anyone cares about your life except you. I sure don't.")

    # Get username
    bot.set_username(input("Username? "))
    print()

    # Print greeting
    print(bot.name + ":", "Hi, I'm", bot.name + "!\n")

    # Simple mainloop
    while True:
        r = input(bot.username + ": ")
        print()
        print(bot.name + ":", bot.get_response(r))
        print()

# Run program
if __name__ == "__main__":
    main()
